<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-N6UCNFO" ignored="3" name="Default test(failed)" tests="2" failures="1" timestamp="2022-02-26T12:12:15 IST" time="0.096" errors="0">
  <testcase name="m2" time="0.032" classname="com.aspire.selenium.TestNG.FailXml"/>
  <testcase name="m3" time="0.015" classname="com.aspire.selenium.TestNG.FailXml">
    <failure type="java.lang.AssertionError" message="null">
      <![CDATA[java.lang.AssertionError: null
at com.aspire.selenium.TestNG.FailXml.m3(FailXml.java:30)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- m3 -->
  <testcase name="m4" time="0.0" classname="com.aspire.selenium.TestNG.FailXml">
    <ignored/>
  </testcase> <!-- m4 -->
  <testcase name="m1" time="0.0" classname="com.aspire.selenium.TestNG.FailXml">
    <ignored/>
  </testcase> <!-- m1 -->
  <testcase name="m5" time="0.0" classname="com.aspire.selenium.TestNG.FailXml">
    <ignored/>
  </testcase> <!-- m5 -->
</testsuite> <!-- Default test(failed) -->
